apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dbmkmaj99-python
  janus-idp.io/tekton: dbmkmaj99-python
  backstage.io/kubernetes-id: dbmkmaj99-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dbmkmaj99-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
