apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dbmkmaj99-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dbmkmaj99-python 
  name: dbmkmaj99-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dbmkmaj99-python
    weight: 100 
